

{
  "language": "python",
  "python": "2.7", "3.5",
  "before_install": [
    "pip install --upgrade pip"
  ],
  "install": [
    "pip install autopep8",
    "pip install coverage",
    "pip install mypy",
    "pip install numpy",
    "pip install pylint"
  ],
  # "before_script": [
  #   "uname -a",
  #   "printenv | sort",
  #   "make versions"
  # ],
  "script": [
  "python unitTest.py"
  ],
  "group": "stable",
  "os": "linux"
}
